version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: house_prices
    ports:
      - "5433:5432"  # Corrected to map host 5433 to container 5432
    volumes:
      - db_data:/var/lib/postgresql/data

  house_price_app:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://user:password@db:5432/house_prices"
    ports:
      - "5001:5001"
    command: >
      sh -c "sleep 5 && python app.py"

volumes:
  db_data:
